version: '3.1'

services:
  sql:
    image: mysql:5.7
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sql_injection
      MYSQL_USER: sql_injection
      MYSQL_PASSWORD: password
    expose: 
      - "3306"
  
  sql-inject:
    image: sql-injection
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - sql
    environment:
      MYSQL_HOST: sql
      MYSQL_PORT: 3306
      MYSQL_USER: sql_injection
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: sql_injection
